package asl.console.ui2;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ServersStateLayout extends VerticalLayout {
	protected Label pageTitleLabel;
	protected VerticalLayout selectServersWrapperLayout;
	protected VerticalLayout selectParametersWrapperLayout;
	protected VerticalLayout serversLayoutWrapper;
	protected HorizontalLayout labelsLayout;
	protected VerticalLayout serversLayout;

	public ServersStateLayout() {
		Design.read(this);
	}
}
